networks:
  app_network:
    driver: bridge
    external: true
    name: ${APP_NETWORK_NAME}

volumes:
  database_data:
    name: ${DATABASE_VOLUME_NAME}

services:
  database:
    image: postgres:latest
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: UTC
      PGTZ: UTC
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - app_network
