volumes:
  runesteel_overlord_si1:
    external: true

services:
  db_runesteel_overlord:
    image: postgres:latest
    container_name: db_runesteel_overlord
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: UTC
      PGTZ: UTC
    volumes:
      - runesteel_overlord_si1:/var/lib/postgresql/data
    networks:
      - micro_network
