volumes:
  ninja_minotaur_logs:

services:
  app_ninja_minotaur:
    image: ${APP_NAME}:latest
    container_name: app_ninja_minotaur
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
      - ${RPC_PORT}:${RPC_PORT}
    depends_on:
      db_runesteel_overlord:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    environment:
      API_PORT: ${API_PORT}
      RPC_PORT: ${RPC_PORT}
      NODE_ENV: production
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?schema=public&timezone=UTC
    volumes:
      - ninja_minotaur_logs:/app/logs
    networks:
      - micro_network
